/*** Autogenerated by WIDL 3.20 from /home/pospeselr/Code/Tor/tor-browser/other-licenses/ia2/AccessibleStates.idl - Do not edit ***/

#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif

#include <rpc.h>
#include <rpcndr.h>

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __accessiblestates_h__
#define __accessiblestates_h__

/* Forward declarations */

/* Headers for imported files */

#include <objidl.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef LONG AccessibleStates;
enum IA2States {
    IA2_STATE_ACTIVE = 0x1,
    IA2_STATE_ARMED = 0x2,
    IA2_STATE_DEFUNCT = 0x4,
    IA2_STATE_EDITABLE = 0x8,
    IA2_STATE_HORIZONTAL = 0x10,
    IA2_STATE_ICONIFIED = 0x20,
    IA2_STATE_INVALID_ENTRY = 0x40,
    IA2_STATE_MANAGES_DESCENDANTS = 0x80,
    IA2_STATE_MODAL = 0x100,
    IA2_STATE_MULTI_LINE = 0x200,
    IA2_STATE_OPAQUE = 0x400,
    IA2_STATE_REQUIRED = 0x800,
    IA2_STATE_SELECTABLE_TEXT = 0x1000,
    IA2_STATE_SINGLE_LINE = 0x2000,
    IA2_STATE_STALE = 0x4000,
    IA2_STATE_SUPPORTS_AUTOCOMPLETION = 0x8000,
    IA2_STATE_TRANSIENT = 0x10000,
    IA2_STATE_VERTICAL = 0x20000,
    IA2_STATE_CHECKABLE = 0x40000,
    IA2_STATE_PINNED = 0x80000
};
/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __accessiblestates_h__ */
