/*** Autogenerated by WIDL 3.20 from /home/pospeselr/Code/Tor/tor-browser/other-licenses/ia2/AccessibleRole.idl - Do not edit ***/

#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif

#include <rpc.h>
#include <rpcndr.h>

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __accessiblerole_h__
#define __accessiblerole_h__

/* Forward declarations */

/* Headers for imported files */

#include <objidl.h>

#ifdef __cplusplus
extern "C" {
#endif

enum IA2Role {
    IA2_ROLE_UNKNOWN = 0,
    IA2_ROLE_CANVAS = 0x401,
    IA2_ROLE_CAPTION = 0x402,
    IA2_ROLE_CHECK_MENU_ITEM = 0x403,
    IA2_ROLE_COLOR_CHOOSER = 0x404,
    IA2_ROLE_DATE_EDITOR = 0x405,
    IA2_ROLE_DESKTOP_ICON = 0x406,
    IA2_ROLE_DESKTOP_PANE = 0x407,
    IA2_ROLE_DIRECTORY_PANE = 0x408,
    IA2_ROLE_EDITBAR = 0x409,
    IA2_ROLE_EMBEDDED_OBJECT = 0x40a,
    IA2_ROLE_ENDNOTE = 0x40b,
    IA2_ROLE_FILE_CHOOSER = 0x40c,
    IA2_ROLE_FONT_CHOOSER = 0x40d,
    IA2_ROLE_FOOTER = 0x40e,
    IA2_ROLE_FOOTNOTE = 0x40f,
    IA2_ROLE_FORM = 0x410,
    IA2_ROLE_FRAME = 0x411,
    IA2_ROLE_GLASS_PANE = 0x412,
    IA2_ROLE_HEADER = 0x413,
    IA2_ROLE_HEADING = 0x414,
    IA2_ROLE_ICON = 0x415,
    IA2_ROLE_IMAGE_MAP = 0x416,
    IA2_ROLE_INPUT_METHOD_WINDOW = 0x417,
    IA2_ROLE_INTERNAL_FRAME = 0x418,
    IA2_ROLE_LABEL = 0x419,
    IA2_ROLE_LAYERED_PANE = 0x41a,
    IA2_ROLE_NOTE = 0x41b,
    IA2_ROLE_OPTION_PANE = 0x41c,
    IA2_ROLE_PAGE = 0x41d,
    IA2_ROLE_PARAGRAPH = 0x41e,
    IA2_ROLE_RADIO_MENU_ITEM = 0x41f,
    IA2_ROLE_REDUNDANT_OBJECT = 0x420,
    IA2_ROLE_ROOT_PANE = 0x421,
    IA2_ROLE_RULER = 0x422,
    IA2_ROLE_SCROLL_PANE = 0x423,
    IA2_ROLE_SECTION = 0x424,
    IA2_ROLE_SHAPE = 0x425,
    IA2_ROLE_SPLIT_PANE = 0x426,
    IA2_ROLE_TEAR_OFF_MENU = 0x427,
    IA2_ROLE_TERMINAL = 0x428,
    IA2_ROLE_TEXT_FRAME = 0x429,
    IA2_ROLE_TOGGLE_BUTTON = 0x42a,
    IA2_ROLE_VIEW_PORT = 0x42b,
    IA2_ROLE_COMPLEMENTARY_CONTENT = 0x42c,
    IA2_ROLE_LANDMARK = 0x42d
};
/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __accessiblerole_h__ */
