/*** Autogenerated by WIDL 3.20 from /home/pospeselr/Code/Tor/tor-browser/other-licenses/ia2/IA2CommonTypes.idl - Do not edit ***/

#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif

#include <rpc.h>
#include <rpcndr.h>

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __ia2commontypes_h__
#define __ia2commontypes_h__

/* Forward declarations */

/* Headers for imported files */


#ifdef __cplusplus
extern "C" {
#endif

enum IA2ScrollType {
    IA2_SCROLL_TYPE_TOP_LEFT = 0,
    IA2_SCROLL_TYPE_BOTTOM_RIGHT = 1,
    IA2_SCROLL_TYPE_TOP_EDGE = 2,
    IA2_SCROLL_TYPE_BOTTOM_EDGE = 3,
    IA2_SCROLL_TYPE_LEFT_EDGE = 4,
    IA2_SCROLL_TYPE_RIGHT_EDGE = 5,
    IA2_SCROLL_TYPE_ANYWHERE = 6
};
enum IA2CoordinateType {
    IA2_COORDTYPE_SCREEN_RELATIVE = 0,
    IA2_COORDTYPE_PARENT_RELATIVE = 1
};
enum IA2TextSpecialOffsets {
    IA2_TEXT_OFFSET_LENGTH = -1,
    IA2_TEXT_OFFSET_CARET = -2
};
enum IA2TableModelChangeType {
    IA2_TABLE_MODEL_CHANGE_INSERT = 0,
    IA2_TABLE_MODEL_CHANGE_DELETE = 1,
    IA2_TABLE_MODEL_CHANGE_UPDATE = 2
};
typedef struct IA2TableModelChange {
    enum IA2TableModelChangeType type;
    LONG firstRow;
    LONG lastRow;
    LONG firstColumn;
    LONG lastColumn;
} IA2TableModelChange;
/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __ia2commontypes_h__ */
