/*** Autogenerated by WIDL 3.20 from /home/pospeselr/Code/Tor/tor-browser/accessible/interfaces/ia2/IA2Typelib.idl - Do not edit ***/

#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif

#include <rpc.h>
#include <rpcndr.h>

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __ia2typelib_h__
#define __ia2typelib_h__

/* Forward declarations */

/* Headers for imported files */

#include <Accessible2.h>
#include <Accessible2_2.h>
#include <Accessible2_3.h>
#include <AccessibleAction.h>
#include <AccessibleApplication.h>
#include <AccessibleComponent.h>
#include <AccessibleDocument.h>
#include <AccessibleEditableText.h>
#include <AccessibleEventId.h>
#include <AccessibleHyperlink.h>
#include <AccessibleHypertext.h>
#include <AccessibleHypertext2.h>
#include <AccessibleImage.h>
#include <AccessibleRelation.h>
#include <AccessibleRole.h>
#include <AccessibleStates.h>
#include <AccessibleTable.h>
#include <AccessibleTable2.h>
#include <AccessibleTableCell.h>
#include <AccessibleText.h>
#include <AccessibleText2.h>
#include <AccessibleValue.h>
#include <IA2CommonTypes.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _MozRemotableHandle {
    LONG fContext;
    LONG hRemote;
} MozRemotableHandle;
typedef MozRemotableHandle *mozHWND;
typedef MozRemotableHandle *mozHMENU;
typedef MozRemotableHandle *mozHACCEL;
typedef MozRemotableHandle *mozHBRUSH;
typedef MozRemotableHandle *mozHFONT;
typedef MozRemotableHandle *mozHDC;
typedef MozRemotableHandle *mozHICON;
typedef MozRemotableHandle *mozHRGN;
typedef MozRemotableHandle *mozHMONITOR;
#if 0
typedef void *HWND;
typedef void *HMENU;
typedef void *HACCEL;
typedef void *HBRUSH;
typedef void *HFONT;
typedef void *HDC;
typedef void *HICON;
typedef void *HRGN;
typedef void *HMONITOR;
#endif // 0

// Type Library Definitions


DEFINE_GUID(LIBID_IAccessible2Lib, 0xce3f726e, 0xd1d3, 0x44fe, 0xb9,0x95, 0xff,0x1d,0xb3,0xb4,0x8b,0x2b);

#ifndef __IAccessible2_FWD_DEFINED__
#define __IAccessible2_FWD_DEFINED__
typedef interface IAccessible2 IAccessible2;
#ifdef __cplusplus
interface IAccessible2;
#endif /* __cplusplus */
#endif

#ifndef __IAccessible2_2_FWD_DEFINED__
#define __IAccessible2_2_FWD_DEFINED__
typedef interface IAccessible2_2 IAccessible2_2;
#ifdef __cplusplus
interface IAccessible2_2;
#endif /* __cplusplus */
#endif

#ifndef __IAccessible2_3_FWD_DEFINED__
#define __IAccessible2_3_FWD_DEFINED__
typedef interface IAccessible2_3 IAccessible2_3;
#ifdef __cplusplus
interface IAccessible2_3;
#endif /* __cplusplus */
#endif

#ifndef __IAccessibleAction_FWD_DEFINED__
#define __IAccessibleAction_FWD_DEFINED__
typedef interface IAccessibleAction IAccessibleAction;
#ifdef __cplusplus
interface IAccessibleAction;
#endif /* __cplusplus */
#endif

#ifndef __IAccessibleApplication_FWD_DEFINED__
#define __IAccessibleApplication_FWD_DEFINED__
typedef interface IAccessibleApplication IAccessibleApplication;
#ifdef __cplusplus
interface IAccessibleApplication;
#endif /* __cplusplus */
#endif

#ifndef __IAccessibleComponent_FWD_DEFINED__
#define __IAccessibleComponent_FWD_DEFINED__
typedef interface IAccessibleComponent IAccessibleComponent;
#ifdef __cplusplus
interface IAccessibleComponent;
#endif /* __cplusplus */
#endif

#ifndef __IAccessibleDocument_FWD_DEFINED__
#define __IAccessibleDocument_FWD_DEFINED__
typedef interface IAccessibleDocument IAccessibleDocument;
#ifdef __cplusplus
interface IAccessibleDocument;
#endif /* __cplusplus */
#endif

#ifndef __IAccessibleEditableText_FWD_DEFINED__
#define __IAccessibleEditableText_FWD_DEFINED__
typedef interface IAccessibleEditableText IAccessibleEditableText;
#ifdef __cplusplus
interface IAccessibleEditableText;
#endif /* __cplusplus */
#endif

#ifndef __IAccessibleHyperlink_FWD_DEFINED__
#define __IAccessibleHyperlink_FWD_DEFINED__
typedef interface IAccessibleHyperlink IAccessibleHyperlink;
#ifdef __cplusplus
interface IAccessibleHyperlink;
#endif /* __cplusplus */
#endif

#ifndef __IAccessibleHypertext_FWD_DEFINED__
#define __IAccessibleHypertext_FWD_DEFINED__
typedef interface IAccessibleHypertext IAccessibleHypertext;
#ifdef __cplusplus
interface IAccessibleHypertext;
#endif /* __cplusplus */
#endif

#ifndef __IAccessibleHypertext2_FWD_DEFINED__
#define __IAccessibleHypertext2_FWD_DEFINED__
typedef interface IAccessibleHypertext2 IAccessibleHypertext2;
#ifdef __cplusplus
interface IAccessibleHypertext2;
#endif /* __cplusplus */
#endif

#ifndef __IAccessibleImage_FWD_DEFINED__
#define __IAccessibleImage_FWD_DEFINED__
typedef interface IAccessibleImage IAccessibleImage;
#ifdef __cplusplus
interface IAccessibleImage;
#endif /* __cplusplus */
#endif

#ifndef __IAccessibleRelation_FWD_DEFINED__
#define __IAccessibleRelation_FWD_DEFINED__
typedef interface IAccessibleRelation IAccessibleRelation;
#ifdef __cplusplus
interface IAccessibleRelation;
#endif /* __cplusplus */
#endif

#ifndef __IAccessibleTable_FWD_DEFINED__
#define __IAccessibleTable_FWD_DEFINED__
typedef interface IAccessibleTable IAccessibleTable;
#ifdef __cplusplus
interface IAccessibleTable;
#endif /* __cplusplus */
#endif

#ifndef __IAccessibleTable2_FWD_DEFINED__
#define __IAccessibleTable2_FWD_DEFINED__
typedef interface IAccessibleTable2 IAccessibleTable2;
#ifdef __cplusplus
interface IAccessibleTable2;
#endif /* __cplusplus */
#endif

#ifndef __IAccessibleTableCell_FWD_DEFINED__
#define __IAccessibleTableCell_FWD_DEFINED__
typedef interface IAccessibleTableCell IAccessibleTableCell;
#ifdef __cplusplus
interface IAccessibleTableCell;
#endif /* __cplusplus */
#endif

#ifndef __IAccessibleText_FWD_DEFINED__
#define __IAccessibleText_FWD_DEFINED__
typedef interface IAccessibleText IAccessibleText;
#ifdef __cplusplus
interface IAccessibleText;
#endif /* __cplusplus */
#endif

#ifndef __IAccessibleText2_FWD_DEFINED__
#define __IAccessibleText2_FWD_DEFINED__
typedef interface IAccessibleText2 IAccessibleText2;
#ifdef __cplusplus
interface IAccessibleText2;
#endif /* __cplusplus */
#endif

#ifndef __IAccessibleValue_FWD_DEFINED__
#define __IAccessibleValue_FWD_DEFINED__
typedef interface IAccessibleValue IAccessibleValue;
#ifdef __cplusplus
interface IAccessibleValue;
#endif /* __cplusplus */
#endif

enum IA2CoordinateType;
enum IA2EventID;
enum IA2Role;
enum IA2ScrollType;
enum IA2States;
enum IA2TableModelChangeType;
enum IA2TextBoundaryType;
enum IA2TextSpecialOffsets;
/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __ia2typelib_h__ */
